
ALTER TABLE device_analytics
  ADD COLUMN IF NOT EXISTS connectivity_type VARCHAR(20) DEFAULT 'wifi',
  ADD COLUMN IF NOT EXISTS power_level DOUBLE PRECISION DEFAULT 85.0,
  ADD COLUMN IF NOT EXISTS signal_strength DOUBLE PRECISION DEFAULT -50.0,
  ADD COLUMN IF NOT EXISTS error_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_refresh_duration DOUBLE PRECISION DEFAULT 19.0;

ALTER TABLE device_health_metrics
  ADD COLUMN IF NOT EXISTS battery_voltage DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS is_charging BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS connectivity_type VARCHAR(20),
  ADD COLUMN IF NOT EXISTS wifi_ssid VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cpu_usage DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS memory_usage DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS storage_usage DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS display_errors INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_error TEXT,
  ADD COLUMN IF NOT EXISTS uptime_seconds INTEGER;
